name: ht_headlines_inmemory
description: In-memory implementation of the `HtHeadlinesClient` interface. It's primarily intended for testing and development purposes.
publish_to: none
repository: https://github.com/headlines-toolkit/ht-headlines-inmemory

environment:
  sdk: ^3.7.0

dependencies:
  ht_headlines_client:
    git: 
      url: https://github.com/headlines-toolkit/ht-headlines-client.git
      
dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.15
  very_good_analysis: ^7.0.0
